# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-20 06:28
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundsTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferAmount', models.IntegerField(default=0, verbose_name='Amount to transfer')),
                ('transferDate', models.DateField(auto_now=True, verbose_name='Date of Funds Transfer')),
                ('transferDescription', models.CharField(default=None, max_length=200, verbose_name='Funds Transfer Description')),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('idNumber', models.CharField(default=None, max_length=30, verbose_name='Customer ID number')),
                ('city', models.CharField(default=None, max_length=20, null=True, verbose_name='Customer City')),
                ('lastAccess', models.DateTimeField(auto_now=True, verbose_name='Time of last successful login')),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'users',
                'abstract': False,
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UtilityCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(default=None, max_length=50, verbose_name=' Company Name')),
                ('companyAccountNum', models.CharField(default=None, max_length=10, verbose_name='Company Account Number')),
                ('companyAccountBalance', models.IntegerField(default=0, verbose_name=' Company Account Balance')),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('accountID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_number', serialize=False, to='bankingapp.UserProfile')),
                ('accountNumber', models.CharField(default=None, max_length=10, verbose_name='Customer Account Number')),
                ('bankName', models.CharField(default=None, max_length=50, verbose_name='Customer Bank Name')),
                ('accountType', models.CharField(choices=[('current', 'Current Account'), ('savings', 'Savings Account')], default='current', max_length=10, verbose_name='Customer Account Type')),
                ('accountBalance', models.IntegerField(default=0, verbose_name=' Customer Current Account Balance')),
                ('createdAt', models.DateField(auto_now_add=True, verbose_name='Date of Account Creation')),
                ('bankBranch', models.CharField(default=None, max_length=50, verbose_name='Name of Account Branch')),
            ],
            options={
                'ordering': ('-createdAt',),
            },
        ),
        migrations.CreateModel(
            name='UtilityPayment',
            fields=[
                ('billName', models.CharField(default=None, max_length=30, verbose_name='Utility Bill Name')),
                ('billAmount', models.IntegerField(default=0, verbose_name='Bill Amount')),
                ('customerName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bankingapp.UserProfile')),
                ('paymentDate', models.DateField(auto_now=True, verbose_name='Date of Payment')),
                ('billDescription', models.CharField(default=None, max_length=100, verbose_name='Description of Bill to be Paid')),
                ('billID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill_ID', to='bankingapp.UtilityCompany')),
            ],
        ),
        migrations.AddField(
            model_name='fundstransfer',
            name='transferID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='fundstransfer',
            name='transferAccount',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_account', to='bankingapp.UserBankAccount'),
        ),
    ]
