# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-22 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilitypayment',
            name='billID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_ID', to='bankingapp.UtilityCompany'),
        ),
        migrations.AlterField(
            model_name='utilitypayment',
            name='customerName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.UserProfile'),
        ),
    ]
