# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-20 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0003_auto_20180520_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='idNumber',
            field=models.CharField(blank=True, max_length=30, verbose_name='Customer ID number'),
        ),
    ]
